import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Table from '../components/Table/Table'
import React from "react"
import axios from "axios"

export default function Home({usersData}) {

  usersData = 0

  return (
    
    <div className={styles.container}>
      
      <Head>
        <title>INDEX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
  
        <Table users={usersData}/>
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps(context) {

  const res = await axios.get('https://worldtimeapi.org/api/ip');
  const usersData = res.data.abbreviation

  return {
    props: {
      usersData : usersData
    }, 
    revalidate: 1
  }

}